version: "3.9"
services:
  pissir-nginx:
    container_name: pissir-nginx
    build:
      context: .
      dockerfile: docker/fe/Dockerfile
    restart: always
    tty: true
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./docker/fe/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/fe/site-enabled/:/etc/nginx/site-enabled/
    depends_on:
      - pissir-be
    networks:
      - pissir_network
  pissir-be:
    container_name: pissir-be
    restart: always
    tty: true
    build: 
      context: .
      dockerfile: docker/be/Dockerfile
    volumes:
      - auth-data:/app/auth-data
    depends_on:
      - pissir-mariadb
      - pissir-mqtt
    networks:
      - pissir_network
  pissir-auth:
    container_name: pissir-auth
    restart: always
    tty: true
    build: 
      context: .
      dockerfile: docker/auth/Dockerfile
    volumes:
      - auth-data:/app/auth-data
    depends_on:
      - pissir-mariadb
    networks:
      - pissir_network
  pissir-mosquito:
    container_name: pissir-mosquito
    restart: always
    tty: true
    build: 
      context: .
      dockerfile: docker/mosquito/Dockerfile
    volumes:
      - auth-data:/app/auth-data
    depends_on:
      - pissir-mariadb
      - pissir-mqtt
    networks:
      - pissir_network
  pissir-mqtt:
    container_name: pissir-mqtt
    image: eclipse-mosquitto:latest
    restart: always
    tty: true
    volumes:
      - ./docker/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    networks:
      - pissir_network
  pissir-mariadb:
    container_name: pissir-mariadb
    image: mariadb:latest
    restart: always
    tty: true
    ports:
      - '3306:3306'
    env_file:
      - docker/mariadb/mariadb.env
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mariadb/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - pissir_network
networks:
  pissir_network:
    driver: bridge

volumes:
  mysql:
    driver: local
  mosquitto-data:
    driver: local
  mosquitto-log:
    driver: local
  auth-data:
    driver: local