version: "3.9"
services:
  pissir-test-mariadb:
    container_name: pissir-test-mariadb
    image: mariadb:latest
    restart: always
    tty: true
    ports:
      - '3307:3306'
    env_file:
      - docker/mariadb/mariadb.env
    volumes:
      - mysql-test:/var/lib/mysql
      - ./docker/mariadb/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - pissir_test_network
networks:
  pissir_test_network:
    driver: bridge

volumes:
  mysql-test:
    driver: local